In [1]:
import numpy as np
np.__version__

'1.20.1'

In [2]:
# numpy array

a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a.shape

(5,)

In [4]:
# type of elements from the array

a.dtype

dtype('int32')

In [5]:
# number of dimensions

a.ndim

1

In [6]:
# total number of elements

a.size

5

In [7]:
# the size in bytes of each element

a.itemsize

4

In [8]:
# change elements from the array

a[0]=5
print(a)

[5 2 3 4 5]


In [9]:
# element-wise math operations

b= a * np.array ([2,0,3,1,4])
b

array([10,  0,  9,  4, 20])

In [10]:
b.sum()

43

In [11]:
# numpy array vs. list

In [12]:
a= np.array([1,2,3,4,5])
l= [1,2,3,4,5]

In [13]:
a

array([1, 2, 3, 4, 5])

In [14]:
l

[1, 2, 3, 4, 5]

In [15]:
# multiplication for each element

a *2

array([ 2,  4,  6,  8, 10])

In [16]:
# l repeated two times. It's same as l + l

l *2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [17]:
l+l

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [18]:
# dot product = sum of the products of all corresponding elements

a= np.array([1,2])
b= np.array([3,4])

In [19]:
dot= 0
for i in range(len(a)):
    dot += a[i] * b[i]
print (dot)

11


In [20]:
# np.dot (array1, array2) .......... dot product using numpy is easier and faster

dot= np.dot( a, b)
dot

11

In [21]:
# array1 . dot(array2)

dot1= a.dot(b)
dot1

11

In [22]:
# speed comparison b/w np.array and list by using timer

# a,b = array
# A,B = list

from timeit import default_timer as timer

a=np.random.randn(1000)
b=np.random.randn(1000)

A=list (np.random.randn(1000))
B=list (np.random.randn(1000))
T=1000

In [23]:
a

array([ 1.56975694e+00,  5.46785665e-01, -3.82293059e-01,  5.66197893e-01,
       -7.25550553e-02, -1.76805752e+00, -1.12018838e+00,  1.02242332e-01,
        1.29038377e-01,  4.04861644e-01, -5.79468563e-01,  1.96057272e+00,
        7.38913195e-01, -9.85131667e-02, -1.48994480e+00,  6.82971503e-01,
        5.92560224e-01, -7.57103575e-01,  7.57577091e-01,  2.47842936e-01,
        9.14814909e-02,  7.07986983e-01, -6.92082410e-01, -2.60718256e+00,
        6.69222991e-02,  3.02205368e-01, -3.20389152e-01, -1.37502171e+00,
        2.28630099e+00, -1.39613079e-01,  9.59897624e-01,  5.00269028e-01,
        9.26388283e-02, -1.09559985e+00, -2.66152954e+00,  5.44100472e-01,
       -1.00494405e+00,  6.13683375e-01, -6.42990515e-02, -1.28753711e+00,
        1.04930138e+00, -1.97375037e+00,  1.08936050e+00, -4.34841403e-01,
        1.08072212e+00, -1.18489898e+00,  2.48296456e-03, -1.68070420e+00,
       -1.28300752e-01,  6.07085810e-01, -3.32869322e-03, -9.81993667e-01,
       -6.06133713e-01, -

In [24]:
A

[1.0366747216366814,
 0.15225152692336694,
 -0.7480514948418053,
 -0.5434848154763513,
 -0.8500355046527114,
 -0.5600350407339587,
 0.03074343644528092,
 0.37280403376393084,
 0.11403999576679394,
 -1.5552218190204252,
 0.816101745403688,
 0.07563254572153642,
 1.4853507614558885,
 -1.4217079943301063,
 -1.6135353385422206,
 -0.005634683540220254,
 0.31704982207614296,
 -0.08565597388435396,
 -0.4569375617767386,
 -0.9804629851203676,
 -1.5466813438064515,
 -0.15236408577809024,
 -1.6642813715273135,
 0.17017419792213684,
 0.961269555260822,
 -0.29385575351427123,
 -1.046219596937685,
 -1.057708146764049,
 -0.4202130120729541,
 0.3721174607056288,
 -0.8172088560325841,
 -0.2807610276985773,
 -0.08599552297977667,
 -0.3342709512789914,
 -0.28222437854372867,
 2.43576140060899,
 -0.25607850325406767,
 0.741328348923239,
 0.4225924832924473,
 1.7934372175333055,
 0.8374157499384935,
 0.2595210647123982,
 -0.5945024790523927,
 0.9462357696904569,
 1.0226119688815187,
 -1.7477728023773955,


In [25]:
# function to use for numpy

def dot1():
    return a.dot(b)

In [26]:
# function to use for list

def dot2():
    dot=0
    for i in range(len(a)):
        dot += a[i]*b[i]
    return dot

In [27]:
start=timer()
for t in range(T):
    dot1()
end=timer()
t1=end-start

In [28]:
start=timer()
for t in range(T):
    dot2()
end=timer()
t2=end-start

In [29]:
print(t1)

0.003270799999999685


In [30]:
print(t2)

0.4265754000000004


In [31]:
# you can see how much faster array is than list

print(t2/t1)

130.41928580165143


In [32]:
# multidimensional nd array

In [33]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [34]:
a.shape

(2, 2)

In [35]:
a.ndim

2

In [36]:
a[0][1]

2

In [37]:
# all rows in column=0

a[:,0]

array([1, 3])

In [38]:
# all columns in row=0

a[0,:]

array([1, 2])

In [39]:
# transpose 

a.T

array([[1, 3],
       [2, 4]])

In [40]:
# matrix multiplication

In [41]:
b= np.array([[1,2],[5,6]])
c = a.dot(b)
d= a*b   # element-wise multiplication

In [42]:
c

array([[11, 14],
       [23, 30]])

In [43]:
d

array([[ 1,  4],
       [15, 24]])

In [44]:
# determinant

c = np.linalg.det(a)
c

-2.0000000000000004

In [45]:
a=np.array([[1,2,3,4], [5,6,7,8], [9,10]])

<ipython-input-45-0292c9db7315>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[1,2,3,4], [5,6,7,8], [9,10]])


In [46]:
a[:,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [47]:
# boolean indexing

a= np.array([[1,2], [3,4], [5,6], [7,8]])
bool_ind= a>3

print(bool_ind)

[[False False]
 [False  True]
 [ True  True]
 [ True  True]]


In [48]:
a[bool_ind]

array([4, 5, 6, 7, 8])

In [49]:
a[a>3]

array([4, 5, 6, 7, 8])

In [50]:
# np.where(): same size with modified values

b= np.where(a>2, a, -1)
b

array([[-1, -1],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [51]:
# access muliple indices at once

a[[0,2,3]]

array([[1, 2],
       [5, 6],
       [7, 8]])

In [52]:
a= np.array( [1,2,3,4,5,6,7,8,9,10] )
a[[0,1,2,3]]

array([1, 2, 3, 4])

In [53]:
# compute the indices where condition is true

even= np.argwhere(a%2==0) .flatten()
print(even)

[1 3 5 7 9]


In [54]:
a[even]

array([ 2,  4,  6,  8, 10])

In [55]:
#np.arange()

a= np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [58]:
# newaxis ... creates new axis in the data

d= a[np.newaxis,:]
d

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [59]:
e= a[:, np.newaxis]
e

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [60]:
# concatenate 2 arrays,

# np.concatenate((a,b), axis=None).... 1-D array

a=np.array([[2,3], [4,5]])
b=np.array([[5,6]])

np.concatenate((a,b), axis=None)

array([2, 3, 4, 5, 5, 6])

In [61]:
np.concatenate((a,b))

array([[2, 3],
       [4, 5],
       [5, 6]])

In [62]:
# hstack: stacks arrays in sequence horizontally (column-wise) 
# vstack: stacks arrays in sequence vertically (row-wise)

In [63]:
a= np.array ([ [2,3], [4,5] ])
b= np.array ([ [3,4], [5,6] ])

c= np.hstack((a,b))
c

array([[2, 3, 3, 4],
       [4, 5, 5, 6]])

In [64]:
d= np.vstack((a,b))
d

array([[2, 3],
       [4, 5],
       [3, 4],
       [5, 6]])

In [65]:
# broadcasting

a=np.array ([[2,3], [4,5], [6,7]])
e=np.array ([[5,6]])

a+e

array([[ 7,  9],
       [ 9, 11],
       [11, 13]])

In [66]:
# functions and axis

a=np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a.sum()

105

In [67]:
# overall sum

print(a.sum(axis=None))

105


In [68]:
print(a.sum(axis=0))

[ 9 11 13 15 17 19 21]


In [69]:
print(a.sum(axis=1))

[28 77]


In [70]:
a.mean()

7.5

In [71]:
a.mean(axis=None)

7.5

In [72]:
a.mean(axis=0)

array([ 4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [73]:
a.mean(axis=1)

array([ 4., 11.])

In [74]:
a.std()

4.031128874149275

In [75]:
a.std(axis=None)

4.031128874149275

In [76]:
a.std(axis=0)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [77]:
a.std(axis=1)

array([2., 2.])

In [78]:
# datatype

In [79]:
a= np.array([1,2])
a.dtype

dtype('int32')

In [80]:
a= np.array([1.0, 2.0])
a.dtype

dtype('float64')

In [81]:
# how to force a particular datatype to an array?

# np.int64 -> 8 bites

a= np.array([1,2], dtype=np.int64)
a

array([1, 2], dtype=int64)

In [82]:
# np.float32 -> 4 bites

a=np.array([1,2], dtype= np.float32)
a

array([1., 2.], dtype=float32)

In [83]:
# copy

a= np.array ([1,2,3])
b= a

b[0]=40
b

array([40,  2,  3])

In [84]:
a

array([40,  2,  3])

In [85]:
 # real copy
    
 # b is just a copy. Doesn't change the original a
    
a= np.array([1,2,3])
b= a.copy() # or np.copy(a)

b[0]=50
b

array([50,  2,  3])

In [86]:
a

array([1, 2, 3])

In [87]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [88]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [89]:
# array of specific values and shape

np.full((3,3), 7.0)

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [90]:
# identity array

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
# linspace

np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [93]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
# random numbers from 0 to 1

# see (2,3) this is a tuple

# returns an array

np.random.random((2,3))

array([[0.19919177, 0.44189069, 0.81199075],
       [0.70945738, 0.9368564 , 0.64112396]])

In [95]:
# see this is a comma-separated list of all different numbers

# returns an array

np.random.randn(2,3)

array([[-0.80251754,  0.59394207, -1.3070362 ],
       [ 0.14533757, -0.40552044, -0.75323296]])

In [96]:
# here, 10,000 elements in a

a= np.random.randn(10000)
a

array([-0.82164357,  0.60487431, -0.97371783, ..., -1.01616314,
        0.4010225 ,  0.66481428])

In [97]:
len(a)

10000

In [98]:
# 8 random elements from 0 to 1

np.random.rand(1,8)

array([[0.86898033, 0.13916046, 0.2229002 , 0.57359617, 0.68928344,
        0.21100702, 0.60498021, 0.09074645]])

In [99]:
np.random.randint(1,10, size=(2,4))

array([[2, 3, 9, 2],
       [8, 6, 1, 3]])

In [100]:
np.random.randint(1,20, size=(3,3))

array([[ 6, 12, 14],
       [ 7, 16,  3],
       [17,  9, 12]])

In [101]:
np.random.randint(10, size=(3,3))

array([[4, 0, 3],
       [8, 3, 0],
       [0, 8, 5]])

In [102]:
np.random.choice(7, 10)

array([6, 6, 1, 2, 2, 2, 2, 0, 3, 6])

In [103]:
np.random.choice(7, size=10)

array([1, 6, 6, 6, 1, 4, 0, 1, 4, 2])

In [104]:
np.random.choice(7, size=(3,3))

array([[3, 0, 5],
       [4, 1, 0],
       [6, 3, 4]])

In [105]:
# to choose 10 random elements from a specific choice of elements

a= np.random.choice([11,22,33,44], size=10)
a

array([44, 11, 11, 22, 44, 22, 22, 22, 33, 33])

In [106]:
a.sort()
a

array([11, 11, 22, 22, 22, 22, 33, 33, 44, 44])

In [107]:
# converts the data type

a.astype(dtype=float)

array([11., 11., 22., 22., 22., 22., 33., 33., 44., 44.])

In [108]:
# linear algebra using eigen value

a= np.array([[1,2], [3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)

[-0.37228132  5.37228132]


In [109]:
print(eigenvectors)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [110]:
print(eigenvectors[:,0])

[-0.82456484  0.56576746]


In [116]:
# solving linear systems

# x1+x2=2200
# 1.5x1 + 4x2 = 5050

a= np.array([[1,1], [1.5, 4]])
b= np.array([2200, 5050])

x= np.linalg.solve(a,b)
x

array([1500.,  700.])

In [ ]:
# how to load csv files on numpy?

# np.genfromtxt is more flexible to use

np.loadtxt('my_file.csv', delimiter=",", dtype=np.float32)

np.genfromtxt('my_file.csv', delimiter=",", dtype=np.float32)